// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlvodbdfaoqdusxrwcnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhsdm9kYmRmYW9xZHVzeHJ3Y25iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTc5NzUsImV4cCI6MjA3MTE3Mzk3NX0.gDFuGZU171JHnV8PW0ijrr1WJmgtJywVFp9EgSEMygE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});